/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d475dda1-b572-40a3-a69b-9712721c9975",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zX9bW6Deo",
    "aws_user_pools_web_client_id": "1oo694t7cc09eb9q09qs7vag4q",
    "oauth": {},
    "aws_user_files_s3_bucket": "corona02042-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
